name: Staging deployment

on: 
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< Updated upstream
=======

    if: contains(github.event.pull_request.labels.*.name, 'stage')
>>>>>>> Stashed changes
